"""init schema 6d usage

Squashed init covering Phases 1–6d (per feedback_preprod_schema). Adds
`usage_tracking` on top of the prior 6c schema; re-seeds
`starter_wardrobe_templates` from JSON so a fresh `alembic upgrade head` lands
with data the outfit generator can draw from on day one.

Revision ID: 6b13316bc906
Revises:
Create Date: 2026-05-07 10:42:40.893060

"""
import json
import uuid
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b13316bc906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TEMPLATES_JSON = (
    Path(__file__).resolve().parents[2] / "data" / "starter_wardrobe_templates.json"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starter_wardrobe_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('style_profile', sa.String(length=50), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starter_wardrobe_templates_template_id'), 'starter_wardrobe_templates', ['template_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.Enum('email', 'apple', 'google', name='auth_method'), nullable=False),
    sa.Column('apple_id', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('agreed_to_terms', sa.Boolean(), nullable=False),
    sa.Column('agreed_to_privacy', sa.Boolean(), nullable=False),
    sa.Column('terms_agreed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_last_step', sa.String(length=50), nullable=True),
    sa.Column('shopping_style', sa.String(length=30), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('style_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('community_share_avatar', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occasion', sa.String(length=50), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ai_reasoning_short', sa.String(length=500), nullable=True),
    sa.Column('ai_reasoning_full', sa.String(length=4000), nullable=True),
    sa.Column('compatibility_score', sa.Integer(), nullable=True),
    sa.Column('weather_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('using_starter_wardrobe', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('generation_method', sa.String(length=50), nullable=False),
    sa.Column('is_logged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('favorited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_is_logged'), 'outfits', ['is_logged'], unique=False)
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('streak_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_logged_date', sa.Date(), nullable=True),
    sa.Column('streak_started_at', sa.Date(), nullable=True),
    sa.Column('total_outfits_logged', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('outfits_generated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mix_and_match_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outfit_limit', sa.Integer(), server_default='21', nullable=False),
    sa.Column('mix_limit', sa.Integer(), server_default='3', nullable=False),
    sa.Column('last_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_reset', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_usage_user_week')
    )
    op.create_index(op.f('ix_usage_tracking_user_id'), 'usage_tracking', ['user_id'], unique=False)
    op.create_table('user_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('unit_system', sa.String(length=10), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encryption_key_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_starter_wardrobes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['starter_wardrobe_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wardrobe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('color_name', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('formality', sa.String(length=20), nullable=True),
    sa.Column('season', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('worn_count', sa.Integer(), nullable=False),
    sa.Column('last_worn', sa.Date(), nullable=True),
    sa.Column('cost_per_wear', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_starter_wardrobe', sa.Boolean(), nullable=False),
    sa.Column('starter_template_id', sa.UUID(), nullable=True),
    sa.Column('added_via', sa.String(length=20), nullable=False),
    sa.Column('ai_detection_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['starter_template_id'], ['starter_wardrobe_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_items_category'), 'wardrobe_items', ['category'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_cost_per_wear'), 'wardrobe_items', ['cost_per_wear'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_is_favorite'), 'wardrobe_items', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_is_starter_wardrobe'), 'wardrobe_items', ['is_starter_wardrobe'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_user_id'), 'wardrobe_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_worn_count'), 'wardrobe_items', ['worn_count'], unique=False)
    op.create_table('wardrobe_transition_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('real_items_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('starter_items_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('percentage_real', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('blending_ratio', sa.Numeric(precision=3, scale=2), server_default='1.00', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('outfit_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('outfit_id', sa.UUID(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shared', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'outfit_id', 'logged_at', name='uq_outfit_history_user_outfit_at')
    )
    op.create_index(op.f('ix_outfit_history_logged_at'), 'outfit_history', ['logged_at'], unique=False)
    op.create_index(op.f('ix_outfit_history_outfit_id'), 'outfit_history', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_outfit_history_user_id'), 'outfit_history', ['user_id'], unique=False)
    op.create_table('wardrobe_wear_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('worn_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', 'worn_date', name='uq_wear_log_user_item_date')
    )
    op.create_index(op.f('ix_wardrobe_wear_log_item_id'), 'wardrobe_wear_log', ['item_id'], unique=False)
    op.create_index(op.f('ix_wardrobe_wear_log_user_id'), 'wardrobe_wear_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_wardrobe_wear_log_worn_date'), 'wardrobe_wear_log', ['worn_date'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('daily_outfit_suggestions', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('outfit_reminders', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('shopping_suggestions', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('wardrobe_insights', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_weekly_summary', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_product_deals', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_pro_offers', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('theme', sa.String(length=10), server_default='light', nullable=False),
    sa.Column('unit_system', sa.String(length=10), server_default='metric', nullable=False),
    sa.Column('style_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.String(length=5000), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_kind'), 'support_tickets', ['kind'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###

    _seed_starter_wardrobe_templates()


def _seed_starter_wardrobe_templates() -> None:
    """Insert the curated starter-wardrobe templates from JSON. Carried over
    from the prior squashed init — re-running this migration on a fresh DB
    reseeds from the file."""
    templates = json.loads(_TEMPLATES_JSON.read_text())
    rows = [
        {
            "id": str(uuid.uuid4()),
            "template_id": t["template_id"],
            "name": t["name"],
            "gender": t.get("gender"),
            "age_range": t.get("age_range"),
            "style_profile": t.get("style_profile"),
            "total_items": len(t["items"]),
            "items": json.dumps(t["items"]),
        }
        for t in templates
    ]
    op.get_bind().execute(
        sa.text(
            """
            INSERT INTO starter_wardrobe_templates
                (id, template_id, name, gender, age_range, style_profile,
                 total_items, items)
            VALUES
                (:id, :template_id, :name, :gender, :age_range, :style_profile,
                 :total_items, CAST(:items AS jsonb))
            """
        ),
        rows,
    )


def downgrade() -> None:
    op.drop_table('support_tickets')
    op.drop_table('user_settings')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wardrobe_wear_log_worn_date'), table_name='wardrobe_wear_log')
    op.drop_index(op.f('ix_wardrobe_wear_log_user_id'), table_name='wardrobe_wear_log')
    op.drop_index(op.f('ix_wardrobe_wear_log_item_id'), table_name='wardrobe_wear_log')
    op.drop_table('wardrobe_wear_log')
    op.drop_index(op.f('ix_outfit_history_user_id'), table_name='outfit_history')
    op.drop_index(op.f('ix_outfit_history_outfit_id'), table_name='outfit_history')
    op.drop_index(op.f('ix_outfit_history_logged_at'), table_name='outfit_history')
    op.drop_table('outfit_history')
    op.drop_table('wardrobe_transition_tracking')
    op.drop_index(op.f('ix_wardrobe_items_worn_count'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_user_id'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_is_starter_wardrobe'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_is_favorite'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_cost_per_wear'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_category'), table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    op.drop_table('user_starter_wardrobes')
    op.drop_table('user_measurements')
    op.drop_index(op.f('ix_usage_tracking_user_id'), table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_table('streak_tracking')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_index(op.f('ix_outfits_is_logged'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_starter_wardrobe_templates_template_id'), table_name='starter_wardrobe_templates')
    op.drop_table('starter_wardrobe_templates')
    # ### end Alembic commands ###
